"""Eğitim Merkezi içeriği / Training Center content.

12 adım adım interaktif eğitim, rol bazlı öneri ve onboarding sihirbazı.
"""

from __future__ import annotations

from app.schemas.system import TutorialOut, TutorialStep


def _step(
    order: int,
    tr_title: str,
    en_title: str,
    tr_body: str,
    en_body: str,
    route: str | None = None,
    tr_hint: str | None = None,
    en_hint: str | None = None,
) -> TutorialStep:
    return TutorialStep(
        order=order,
        title_tr=tr_title,
        title_en=en_title,
        body_tr=tr_body,
        body_en=en_body,
        target_route=route,
        action_hint_tr=tr_hint,
        action_hint_en=en_hint,
    )


TUTORIALS: list[TutorialOut] = [
    TutorialOut(
        id="first_student",
        title_tr="İlk Öğrencinizi Oluşturun",
        title_en="Create Your First Student",
        description_tr="Öğrenci kaydı açmayı, veli bağlamayı ve seviye atamayı öğrenin.",
        description_en="Learn to create a student record, link a guardian and set a level.",
        category="basics",
        roles=[
            "reception",
            "operations_manager",
            "school_director",
            "system_admin",
            "sales_marketing",
        ],
        estimated_minutes=5,
        steps=[
            _step(
                1,
                "Öğrenciler ekranını açın",
                "Open the Students screen",
                "Sol menüden **Öğrenciler**'e tıklayın. Tüm kayıtlı öğrencileri burada görürsünüz.",
                "Click **Students** in the left menu. All registered students are listed here.",
                "/students",
                "Sol menü > Öğrenciler",
                "Left menu > Students",
            ),
            _step(
                2,
                "Yeni Öğrenci butonuna basın",
                "Click New Student",
                "Sağ üstteki **Yeni Öğrenci** butonu kayıt formunu açar. Kısayol: Ctrl+K > 'Yeni öğrenci'.",
                "The **New Student** button at the top right opens the form. Shortcut: Ctrl+K > 'New student'.",
                "/students?action=new",
            ),
            _step(
                3,
                "Zorunlu alanları doldurun",
                "Fill in the required fields",
                "Ad, soyad ve doğum tarihi zorunludur. Öğrenci numarası boş bırakılırsa otomatik üretilir (OGR00001).",
                "First name, last name and birth date are required. Leaving the student number blank auto-generates one (OGR00001).",
            ),
            _step(
                4,
                "Yüzme seviyesi ve grup seçin",
                "Choose swim level and group",
                "Seviye (Başlangıç → Elit) ders planlamasında ve raporlarda kullanılır. Grup atamak zorunlu değildir.",
                "The level (Beginner → Elite) is used in scheduling and reports. Assigning a group is optional.",
            ),
            _step(
                5,
                "Veli bağlayın",
                "Link a guardian",
                "Öğrenci 18 yaşından küçükse veli bağlamanız önerilir. Bir velinin birden fazla öğrencisi olabilir.",
                "If the student is under 18, linking a guardian is recommended. A guardian can have multiple students.",
            ),
            _step(
                6,
                "KVKK onayını işaretleyin",
                "Tick the data-protection consent",
                "Kişisel veri işleme için açık rıza kaydı tutulur. Onay yoksa CAIO uyarı üretir.",
                "Explicit consent for personal data processing is recorded. Without it, CAIO raises a warning.",
            ),
            _step(
                7,
                "Kaydedin ve profili inceleyin",
                "Save and review the profile",
                "Kaydettikten sonra öğrenci profilinde devam oranı, ödeme geçmişi ve performans sekmelerini görürsünüz.",
                "After saving, the student profile shows attendance rate, payment history and performance tabs.",
            ),
        ],
    ),
    TutorialOut(
        id="first_instructor",
        title_tr="İlk Eğitmeninizi Oluşturun",
        title_en="Create Your First Instructor",
        description_tr="Eğitmen kaydı, uzmanlık, sertifika ve müsaitlik takvimi.",
        description_en="Instructor record, specialties, certificates and availability.",
        category="basics",
        roles=["hr", "operations_manager", "school_director", "system_admin"],
        estimated_minutes=5,
        steps=[
            _step(
                1,
                "Eğitmenler ekranını açın",
                "Open the Instructors screen",
                "Sol menüden **Eğitmenler**'e gidin.",
                "Go to **Instructors** in the left menu.",
                "/instructors",
            ),
            _step(
                2,
                "Yeni eğitmen ekleyin",
                "Add a new instructor",
                "Ad, soyad ve unvan girin. Personel numarası otomatik üretilir (EGT0001).",
                "Enter first name, last name and title. The employee number is auto-generated (EGT0001).",
            ),
            _step(
                3,
                "Uzmanlık alanlarını seçin",
                "Select specialties",
                "Bebek yüzme, adaptif yüzme, yarışma antrenörlüğü gibi uzmanlıklar ders atamasında filtre olarak kullanılır.",
                "Specialties such as baby swimming, adaptive swimming or competition coaching are used as filters when assigning lessons.",
            ),
            _step(
                4,
                "Sertifika ekleyin",
                "Add certificates",
                "TYF antrenörlük belgesi, cankurtaran ve ilk yardım sertifikalarını son geçerlilik tarihiyle ekleyin. Sistem süresi dolanları işaretler.",
                "Add coaching, lifeguard and first-aid certificates with expiry dates. The system flags expired ones.",
            ),
            _step(
                5,
                "Müsaitlik takvimini tanımlayın",
                "Define the availability calendar",
                "Haftalık çalışma saatlerini girin. Ders planlarken bu saatlerin dışına atama yaparsanız uyarı alırsınız.",
                "Enter weekly working hours. Scheduling outside these hours produces a warning.",
            ),
            _step(
                6,
                "İzin günlerini kaydedin",
                "Record leave days",
                "İzinli olduğu tarihlerde o eğitmene ders atanırsa sistem uyarı verir.",
                "If a lesson is assigned during leave, the system warns you.",
            ),
        ],
    ),
    TutorialOut(
        id="first_pool",
        title_tr="İlk Havuz ve Kulvarınızı Tanımlayın",
        title_en="Define Your First Pool and Lanes",
        description_tr="Havuz ölçüleri, kulvarlar, çalışma saatleri ve su kalitesi.",
        description_en="Pool dimensions, lanes, operating hours and water quality.",
        category="basics",
        roles=[
            "operations_manager",
            "school_director",
            "system_admin",
            "pool_technician",
        ],
        estimated_minutes=4,
        steps=[
            _step(
                1,
                "Havuzlar ekranını açın",
                "Open the Pools screen",
                "Sol menüden **Havuzlar**'a gidin.",
                "Go to **Pools** in the left menu.",
                "/pools",
            ),
            _step(
                2,
                "Havuz bilgilerini girin",
                "Enter pool details",
                "Uzunluk (25 m / 50 m), genişlik, derinlik ve kulvar sayısı girin. Kulvar sayısına göre kulvarlar otomatik oluşturulur.",
                "Enter length (25 m / 50 m), width, depth and lane count. Lanes are created automatically.",
            ),
            _step(
                3,
                "Çalışma saatlerini belirleyin",
                "Set operating hours",
                "Açılış ve kapanış saatleri, ders planlarken saat dışı uyarısı üretmek için kullanılır.",
                "Opening and closing hours are used to warn when scheduling outside hours.",
            ),
            _step(
                4,
                "Kulvarları düzenleyin",
                "Configure lanes",
                "Her kulvara isim ve amaç (Eğitim, Serbest, Yarışma) verebilirsiniz. Kullanılmayan kulvarları pasife alın.",
                "You can name each lane and set a purpose (Training, Free, Competition). Deactivate unused lanes.",
            ),
            _step(
                5,
                "Su kalitesi ölçümü girin",
                "Log a water-quality measurement",
                "pH (6.8-7.6) ve klor (0.5-3.0 ppm) sınır dışındaysa sistem otomatik uyarı bildirimi gönderir.",
                "If pH (6.8-7.6) or chlorine (0.5-3.0 ppm) is out of range, the system sends an automatic alert.",
            ),
        ],
    ),
    TutorialOut(
        id="first_schedule",
        title_tr="İlk Ders Programınızı Hazırlayın",
        title_en="Build Your First Lesson Schedule",
        description_tr="Tekil ders, tekrarlanan seri ve çakışma denetimi.",
        description_en="Single lessons, recurring series and conflict detection.",
        category="operations",
        roles=[
            "reception",
            "operations_manager",
            "head_coach",
            "school_director",
            "system_admin",
        ],
        estimated_minutes=8,
        steps=[
            _step(
                1,
                "Takvimi açın",
                "Open the calendar",
                "Sol menüden **Takvim**'e gidin. Günlük, haftalık ve aylık görünümler arasında geçiş yapabilirsiniz.",
                "Go to **Calendar**. You can switch between daily, weekly and monthly views.",
                "/calendar",
            ),
            _step(
                2,
                "Boş kulvar bulun",
                "Find a free lane",
                "**Kulvar Planı** sekmesi seçilen gün için hangi kulvarın hangi saatte boş olduğunu gösterir.",
                "The **Lane Plan** tab shows which lane is free at which hour for the selected day.",
            ),
            _step(
                3,
                "Yeni ders oluşturun",
                "Create a lesson",
                "Ders türü, havuz, kulvar, eğitmen ve saat seçin. Sistem kaydetmeden önce çakışma denetimi yapar.",
                "Choose lesson type, pool, lane, instructor and time. The system checks conflicts before saving.",
            ),
            _step(
                4,
                "Çakışma uyarılarını okuyun",
                "Read conflict warnings",
                "Aynı saatte aynı eğitmen, kulvar veya öğrenci iki derste olamaz. Kırmızı uyarılar engelleyicidir; sarı uyarılar bilgilendirmedir.",
                "The same instructor, lane or student cannot be in two lessons at once. Red warnings block; yellow ones inform.",
            ),
            _step(
                5,
                "Tekrarlanan seri oluşturun",
                "Create a recurring series",
                "Haftanın günlerini (ör. Salı + Perşembe) ve tarih aralığını seçin. Sistem tüm dersleri üretir, çakışan tarihleri atlar.",
                "Pick weekdays (e.g. Tuesday + Thursday) and a date range. All lessons are generated; conflicting dates are skipped.",
            ),
            _step(
                6,
                "Öğrenci kaydedin",
                "Enrol students",
                "Derse öğrenci eklerken kontenjan ve öğrencinin başka dersle çakışması denetlenir.",
                "When adding students, capacity and student-level conflicts are checked.",
            ),
            _step(
                7,
                "Sürükle-bırak ile taşıyın",
                "Move by drag and drop",
                "Takvimde dersi sürükleyerek saatini değiştirebilirsiniz; çakışma denetimi otomatik çalışır.",
                "Drag a lesson in the calendar to change its time; conflict checks run automatically.",
            ),
        ],
    ),
    TutorialOut(
        id="take_attendance",
        title_tr="Yoklama Alın",
        title_en="Take Attendance",
        description_tr="Manuel, QR ve kart ile yoklama; telafi dersi atama.",
        description_en="Manual, QR and card attendance; assigning make-up lessons.",
        category="operations",
        roles=[
            "reception",
            "swim_instructor",
            "kids_instructor",
            "head_coach",
            "operations_manager",
        ],
        estimated_minutes=5,
        steps=[
            _step(
                1,
                "Yoklama ekranını açın",
                "Open the attendance screen",
                "Sol menüden **Yoklama**'ya gidin veya takvimde bir derse tıklayıp 'Yoklama Al' deyin.",
                "Go to **Attendance**, or click a lesson in the calendar and choose 'Take attendance'.",
                "/attendance",
            ),
            _step(
                2,
                "Dersi seçin",
                "Select the lesson",
                "Bugünün dersleri listelenir. Yoklaması alınmamış dersler işaretlidir.",
                "Today's lessons are listed. Lessons without attendance are flagged.",
            ),
            _step(
                3,
                "Durumları işaretleyin",
                "Mark statuses",
                "Geldi, Gelmedi, Geç Geldi, Mazeretli, İptal, Telafi seçenekleri vardır. Geç gelenler için dakika girebilirsiniz.",
                "Options: Present, Absent, Late, Excused, Cancelled, Make-up. You can enter minutes for late arrivals.",
            ),
            _step(
                4,
                "Ders hakkı düşümünü kontrol edin",
                "Check credit consumption",
                "'Geldi' ve 'Geç Geldi' işaretlendiğinde öğrencinin paketinden bir ders hakkı düşer. Bunu kapatabilirsiniz.",
                "Marking 'Present' or 'Late' consumes one lesson credit from the package. This can be disabled.",
            ),
            _step(
                5,
                "QR kod kullanın",
                "Use QR check-in",
                "Ders için QR üretip girişte okutabilirsiniz. Öğrenci kartı oluşturmak için öğrenci profilini kullanın.",
                "Generate a QR for the lesson and scan at the entrance. Create student cards from the student profile.",
            ),
            _step(
                6,
                "Telafi dersi atayın",
                "Assign a make-up lesson",
                "Mazeretli veya gelmemiş öğrenciye başka bir dersi telafi olarak atayabilirsiniz.",
                "You can assign another lesson as a make-up for excused or absent students.",
            ),
        ],
    ),
    TutorialOut(
        id="membership_payment",
        title_tr="Üyelik ve Ödeme İşlemi",
        title_en="Membership and Payment",
        description_tr="Paket satışı, ödeme alma, dondurma ve yenileme.",
        description_en="Selling packages, taking payments, freezing and renewing.",
        category="finance",
        roles=[
            "reception",
            "finance",
            "sales_marketing",
            "school_director",
            "system_admin",
        ],
        estimated_minutes=7,
        steps=[
            _step(
                1,
                "Paketleri inceleyin",
                "Review packages",
                "**Üyelikler > Paketler** sekmesinde 4/8/12 ders, aylık, yıllık ve özel ders paketleri tanımlıdır.",
                "Under **Memberships > Packages** you'll find 4/8/12-lesson, monthly, annual and private packages.",
                "/memberships",
            ),
            _step(
                2,
                "Yeni üyelik oluşturun",
                "Create a membership",
                "Öğrenci ve paket seçin. Bitiş tarihi paket süresine göre otomatik hesaplanır.",
                "Pick a student and package. The end date is calculated from the package duration.",
            ),
            _step(
                3,
                "İndirim uygulayın",
                "Apply a discount",
                "Kardeş indirimi gibi durumlarda indirim tutarı ve gerekçesi girilebilir; rapora yansır.",
                "For cases like sibling discounts you can enter an amount and reason; it appears in reports.",
            ),
            _step(
                4,
                "Ödeme alın",
                "Take a payment",
                "Nakit, POS, havale veya online seçin. Fiş numarası otomatik üretilir (FIS000001).",
                "Choose cash, card, transfer or online. The receipt number is generated automatically (FIS000001).",
            ),
            _step(
                5,
                "Üyeliği dondurun",
                "Freeze a membership",
                "Hastalık veya tatil durumunda dondurun; bitiş tarihi dondurma süresi kadar otomatik ötelenir.",
                "Freeze for illness or holiday; the end date is extended by the frozen duration.",
            ),
            _step(
                6,
                "Yenileme yapın",
                "Renew",
                "Süresi biten üyeliği yenilediğinizde yeni dönem otomatik başlar; eski üyelik kapanır.",
                "Renewing an expiring membership starts a new period and closes the old one.",
            ),
        ],
    ),
    TutorialOut(
        id="performance_record",
        title_tr="Performans Kaydı ve Analizi",
        title_en="Performance Recording and Analysis",
        description_tr="Derece girişi, kişisel rekor takibi ve gelişim grafikleri.",
        description_en="Entering times, tracking personal bests and progress charts.",
        category="sports",
        roles=["head_coach", "swim_coach", "swim_instructor", "conditioning_coach"],
        estimated_minutes=6,
        steps=[
            _step(
                1,
                "Performans ekranını açın",
                "Open the Performance screen",
                "Sol menüden **Performans**'a gidin.",
                "Go to **Performance** in the left menu.",
                "/performance",
            ),
            _step(
                2,
                "Yeni derece girin",
                "Enter a new time",
                "Sporcu, stil (serbest/sırt/kurbağalama/kelebek), mesafe ve dereceyi girin. Derece `1:35.12` veya `95.12` biçiminde yazılabilir.",
                "Enter athlete, stroke, distance and time. Times accept `1:35.12` or `95.12`.",
            ),
            _step(
                3,
                "Ek ölçümleri kaydedin",
                "Record extra metrics",
                "Split süreleri, kulaç sayısı, stroke rate, çıkış reaksiyonu ve dönüş süresi girilebilir.",
                "You can record splits, stroke count, stroke rate, reaction time and turn time.",
            ),
            _step(
                4,
                "Kişisel rekoru izleyin",
                "Track personal bests",
                "Yeni derece önceki en iyiden hızlıysa sistem otomatik olarak kişisel rekor işaretler.",
                "If the new time beats the previous best, the system marks it as a personal best automatically.",
            ),
            _step(
                5,
                "Gelişim analizini okuyun",
                "Read the progress analysis",
                "Sporcu özetinde ortalama, medyan, standart sapma, 30/90 günlük değişim ve eğilim hesaplanır. Bu veriler gerçektir, AI tahmini değildir.",
                "The athlete summary computes mean, median, standard deviation, 30/90-day change and trend. These are real data, not AI predictions.",
            ),
            _step(
                6,
                "AI yorumu isteyin",
                "Ask for an AI interpretation",
                "AI Merkezi'nden 'Öğrenci performansını analiz et' promptunu çalıştırın. Gerçek veri ve AI yorumu ayrı bölümlerde gösterilir.",
                "Run the 'Analyse student performance' prompt in the AI Center. Real data and AI interpretation are shown separately.",
            ),
        ],
    ),
    TutorialOut(
        id="statistics_report",
        title_tr="İstatistik Raporu Oluşturun",
        title_en="Create a Statistics Report",
        description_tr="İstatistik merkezi, KPI hedefleri ve rapor dışa aktarma.",
        description_en="Statistics center, KPI targets and report export.",
        category="management",
        roles=["school_director", "operations_manager", "finance", "system_admin"],
        estimated_minutes=6,
        steps=[
            _step(
                1,
                "İstatistik Merkezi'ni açın",
                "Open the Statistics Center",
                "Sol menüden **İstatistikler**'e gidin.",
                "Go to **Statistics** in the left menu.",
                "/statistics",
            ),
            _step(
                2,
                "Dönem seçin",
                "Choose a period",
                "Bugün, bu hafta, bu ay, 3 ay, yıl veya özel tarih aralığı seçebilirsiniz. Önceki dönemle otomatik karşılaştırılır.",
                "Choose today, this week, month, quarter, year or a custom range. It compares with the previous period automatically.",
            ),
            _step(
                3,
                "Yoğunluk haritasını inceleyin",
                "Inspect the heatmap",
                "Havuz sekmesindeki ısı haritası gün ve saat bazında doluluğu gösterir; boş saatleri değerlendirmek için kullanın.",
                "The heatmap on the Pools tab shows occupancy by day and hour; use it to fill quiet slots.",
            ),
            _step(
                4,
                "KPI hedefi belirleyin",
                "Set KPI targets",
                "Devam %90, doluluk %80, tahsilat %95 gibi hedefler girin. Gerçekleşen değerler hedefle karşılaştırılır.",
                "Enter targets such as attendance 90%, occupancy 80%, collection 95%. Actuals are compared to targets.",
            ),
            _step(
                5,
                "Rapor oluşturun",
                "Build a report",
                "**Raporlar** ekranından rapor türü, tarih aralığı ve filtreleri seçin, önizleyin.",
                "On the **Reports** screen choose a report type, date range and filters, then preview.",
                "/reports",
            ),
            _step(
                6,
                "PDF/Excel/CSV dışa aktarın",
                "Export to PDF/Excel/CSV",
                "Dışa aktarma butonu seçtiğiniz biçimde dosya indirir. Türkçe karakterler korunur.",
                "The export button downloads the file in the chosen format. Turkish characters are preserved.",
            ),
        ],
    ),
    TutorialOut(
        id="backup_data",
        title_tr="Verilerinizi Yedekleyin",
        title_en="Back Up Your Data",
        description_tr="Manuel yedek, doğrulama, otomatik yedekleme ve geri yükleme.",
        description_en="Manual backup, verification, scheduling and restore.",
        category="system",
        roles=["system_admin", "school_director"],
        estimated_minutes=6,
        steps=[
            _step(
                1,
                "Yedekleme ekranını açın",
                "Open the backup screen",
                "**Ayarlar > Sistem > Yedekleme ve Geri Yükleme** bölümüne gidin.",
                "Go to **Settings > System > Backup and Restore**.",
                "/settings?tab=backup",
            ),
            _step(
                2,
                "Şimdi yedekleyin",
                "Back up now",
                "'Şimdi Yedekle' butonu veritabanı, belgeler ve ayarları tek ZIP arşivinde toplar. API anahtarları yedeğe DAHİL EDİLMEZ.",
                "'Back up now' bundles the database, documents and settings into one ZIP. API keys are NOT included.",
            ),
            _step(
                3,
                "Bütünlüğü doğrulayın",
                "Verify integrity",
                "Her yedek otomatik doğrulanır: dosya var mı, checksum doğru mu, veritabanı açılıyor mu, kayıt sayıları tutuyor mu.",
                "Each backup is verified automatically: file exists, checksum matches, database opens, record counts match.",
            ),
            _step(
                4,
                "Otomatik yedeklemeyi açın",
                "Enable scheduled backups",
                "Her gün 23:00, her hafta Pazar veya her ayın ilk günü gibi politikalar tanımlayabilirsiniz.",
                "You can define policies such as daily at 23:00, weekly on Sunday, or monthly.",
            ),
            _step(
                5,
                "Saklama politikasını ayarlayın",
                "Configure retention",
                "Son 7 gün, 4 hafta ve 12 ay tutulur. Önemli yedekleri 'Korunan' işaretleyin; otomatik silinmezler.",
                "Keeps last 7 days, 4 weeks and 12 months. Mark important backups as 'Protected' so they are never auto-deleted.",
            ),
            _step(
                6,
                "Geri yüklemeyi öğrenin",
                "Learn how to restore",
                "Geri yükleme önce yedeği doğrular, mevcut sistemin güvenlik yedeğini alır, değişecekleri gösterir ve onay ister. Hata olursa otomatik geri döner.",
                "Restore first verifies the backup, takes a safety backup, shows what will change and asks for confirmation. On failure it rolls back automatically.",
            ),
        ],
    ),
    TutorialOut(
        id="local_ai",
        title_tr="Local AI Kullanımı (LM Studio)",
        title_en="Using Local AI (LM Studio)",
        description_tr="Yerel model bağlantısı, gizlilik ve test.",
        description_en="Local model connection, privacy and testing.",
        category="ai",
        roles=["system_admin", "school_director", "head_coach", "operations_manager"],
        estimated_minutes=5,
        steps=[
            _step(
                1,
                "LM Studio sunucusunu başlatın",
                "Start the LM Studio server",
                "LM Studio uygulamasında **Developer > Start Server** ile yerel sunucuyu açın. Varsayılan adres http://localhost:1234",
                "In LM Studio open **Developer > Start Server**. Default address: http://localhost:1234",
            ),
            _step(
                2,
                "AI Merkezi'ni açın",
                "Open the AI Center",
                "Sol menüden **AI Merkezi**'ne gidin. Sağlayıcı durumu, gecikme ve model sayısı görünür.",
                "Go to **AI Center**. Provider status, latency and model count are shown.",
                "/ai",
            ),
            _step(
                3,
                "Bağlantı testini çalıştırın",
                "Run the connection test",
                "Test 6 aşamayı kontrol eder: bağlantı, model listesi, basit istem, JSON çıktısı, zaman aşımı, akış.",
                "The test checks six stages: connection, model list, simple prompt, JSON output, timeout, streaming.",
            ),
            _step(
                4,
                "Model seçin",
                "Choose a model",
                "Görev türüne göre model seçilir. Yetenek bilgisi API tarafından bildirilmediyse 'doğrulanmamış' olarak işaretlenir.",
                "Models are chosen by task type. If capability isn't reported by the API it is marked 'unverified'.",
            ),
            _step(
                5,
                "Gizliliği anlayın",
                "Understand privacy",
                "Yerel modelde veriler bilgisayarınızdan çıkmaz. Hassas öğrenci verisi için yalnızca yerel AI kullanmak isterseniz modu 'Local' yapın.",
                "With a local model your data never leaves the computer. To use only local AI for sensitive data set the mode to 'Local'.",
            ),
        ],
    ),
    TutorialOut(
        id="cloud_ai",
        title_tr="Cloud AI Kullanımı (NVIDIA)",
        title_en="Using Cloud AI (NVIDIA)",
        description_tr="API anahtarı güvenliği, fallback ve maliyet kontrolü.",
        description_en="API key security, fallback and cost control.",
        category="ai",
        roles=["system_admin", "school_director"],
        estimated_minutes=5,
        steps=[
            _step(
                1,
                "API anahtarı alın",
                "Obtain an API key",
                "https://build.nvidia.com adresinde hesabınıza girip API anahtarı oluşturun. Bu adımı programın dışında, kendiniz yapmalısınız.",
                "Sign in at https://build.nvidia.com and create an API key. You must do this yourself, outside the application.",
            ),
            _step(
                2,
                "Anahtarı .env dosyasına yazın",
                "Store the key in .env",
                "Anahtarı **Ayarlar > AI** ekranından girin. Anahtar `.env` dosyasına yazılır, veritabanına veya loglara ASLA kaydedilmez.",
                "Enter the key in **Settings > AI**. It is written to `.env` and NEVER stored in the database or logs.",
            ),
            _step(
                3,
                "Bağlantıyı test edin",
                "Test the connection",
                "AI Merkezi'nden NVIDIA sağlayıcısı için bağlantı testi çalıştırın. Test çıktısında anahtar maskelenir.",
                "Run the connection test for the NVIDIA provider. The key is masked in test output.",
            ),
            _step(
                4,
                "Fallback zincirini ayarlayın",
                "Configure the fallback chain",
                "Örnek: `local,nvidia`. Yerel model yanıt vermezse otomatik olarak buluta geçilir.",
                "Example: `local,nvidia`. If the local model fails the system falls back to the cloud.",
            ),
            _step(
                5,
                "Maliyeti izleyin",
                "Monitor cost",
                "AI Merkezi token kullanımını gösterir. CAIO bulut kullanımı yüksekse maliyet uyarısı üretir.",
                "The AI Center shows token usage. CAIO raises a cost warning if cloud usage is high.",
            ),
        ],
    ),
    TutorialOut(
        id="ai_developer",
        title_tr="AI Developer Console Kullanımı",
        title_en="Using the AI Developer Console",
        description_tr="Güvenli kod değişikliği: plan, diff, test, onay, geri alma.",
        description_en="Safe code changes: plan, diff, test, approve, rollback.",
        category="ai",
        roles=["system_admin"],
        estimated_minutes=8,
        steps=[
            _step(
                1,
                "Güvenlik politikasını okuyun",
                "Read the security policy",
                "Konsol açılışında ajanın neleri yapıp yapamayacağı listelenir. Proje dışına yazma, registry, disk ve hesap işlemleri YASAKTIR.",
                "The console lists what the agent can and cannot do. Writing outside the project, registry, disk and account operations are FORBIDDEN.",
                "/ai-developer",
            ),
            _step(
                2,
                "Görevinizi yazın",
                "Describe your task",
                "Örnek: 'Öğrenci ekranına Excel export ekle.' Açık ve dosya/modül adı içeren istemler daha iyi sonuç verir.",
                "Example: 'Add Excel export to the students screen.' Clear prompts naming files or modules work best.",
            ),
            _step(
                3,
                "Planı inceleyin",
                "Review the plan",
                "Ajan READ → SEARCH → ANALYZE → PLAN adımlarını çalıştırır ve hangi dosyaları neden değiştireceğini açıklar.",
                "The agent runs READ → SEARCH → ANALYZE → PLAN and explains which files it will change and why.",
            ),
            _step(
                4,
                "Diff'i satır satır okuyun",
                "Read the diff line by line",
                "Hiçbir değişiklik siz onaylamadan uygulanmaz. Yeşil satırlar eklenen, kırmızı satırlar silinen koddur.",
                "Nothing is applied until you approve. Green lines are additions, red lines are deletions.",
            ),
            _step(
                5,
                "Testleri çalıştırın",
                "Run the tests",
                "Yamayı uygulamadan önce mevcut testlerin geçtiğini doğrulayın.",
                "Verify the existing tests pass before applying the patch.",
            ),
            _step(
                6,
                "Onaylayın ve uygulayın",
                "Approve and apply",
                "Uygulama öncesi otomatik checkpoint alınır. Testler başarısız olursa değişiklikler OTOMATİK geri alınır.",
                "A checkpoint is created automatically. If tests fail, changes are rolled back AUTOMATICALLY.",
            ),
            _step(
                7,
                "Gerekirse geri alın",
                "Roll back if needed",
                "Checkpoint listesinden istediğiniz noktaya dönebilirsiniz.",
                "You can return to any point from the checkpoint list.",
            ),
        ],
    ),
]

TUTORIAL_INDEX = {tutorial.id: tutorial for tutorial in TUTORIALS}

TRACKS = [
    {
        "id": "basics",
        "title_tr": "Başlangıç Eğitimi",
        "title_en": "Getting Started",
        "tutorials": [
            "first_student",
            "first_instructor",
            "first_pool",
            "first_schedule",
            "take_attendance",
        ],
    },
    {
        "id": "operations",
        "title_tr": "Operasyon Eğitimi",
        "title_en": "Operations Training",
        "tutorials": ["first_schedule", "take_attendance", "membership_payment"],
    },
    {
        "id": "management",
        "title_tr": "Yönetici Eğitimi",
        "title_en": "Manager Training",
        "tutorials": ["statistics_report", "membership_payment", "backup_data"],
    },
    {
        "id": "sports",
        "title_tr": "Antrenör Eğitimi",
        "title_en": "Coach Training",
        "tutorials": ["performance_record", "first_schedule", "take_attendance"],
    },
    {
        "id": "ai",
        "title_tr": "Yapay Zekâ Eğitimi",
        "title_en": "AI Training",
        "tutorials": ["local_ai", "cloud_ai", "ai_developer"],
    },
    {
        "id": "system",
        "title_tr": "Sistem Yöneticisi Eğitimi",
        "title_en": "System Administrator Training",
        "tutorials": ["backup_data", "local_ai", "ai_developer"],
    },
]

# Rol bazlı önerilen eğitim izleri
ROLE_TRACKS: dict[str, list[str]] = {
    "reception": ["basics", "operations"],
    "swim_instructor": ["sports"],
    "kids_instructor": ["sports"],
    "baby_instructor": ["sports"],
    "private_instructor": ["sports"],
    "adaptive_instructor": ["sports"],
    "conditioning_coach": ["sports"],
    "swim_coach": ["sports"],
    "head_coach": ["sports", "management"],
    "school_director": ["management", "basics", "ai"],
    "operations_manager": ["operations", "management"],
    "finance": ["management"],
    "hr": ["basics"],
    "sales_marketing": ["basics", "management"],
    "system_admin": ["system", "ai", "basics", "management"],
    "pool_technician": ["basics"],
    "lifeguard": ["basics"],
    "medical_staff": ["basics"],
    "parent": [],
    "student": [],
    "athlete": ["sports"],
}


ONBOARDING_STEPS = [
    {
        "id": "organization",
        "title_tr": "Kurum Bilgileri",
        "title_en": "Organisation Details",
        "description_tr": "Okul adı, iletişim, para birimi ve dil.",
        "description_en": "School name, contact, currency and language.",
        "route": "/settings?tab=general",
    },
    {
        "id": "admin",
        "title_tr": "İlk Yönetici",
        "title_en": "First Administrator",
        "description_tr": "Yönetici parolasını değiştirin.",
        "description_en": "Change the administrator password.",
        "route": "/settings?tab=profile",
    },
    {
        "id": "pool",
        "title_tr": "Havuz Oluştur",
        "title_en": "Create a Pool",
        "description_tr": "En az bir havuz tanımlayın.",
        "description_en": "Define at least one pool.",
        "route": "/pools?action=new",
    },
    {
        "id": "lanes",
        "title_tr": "Kulvarları Tanımla",
        "title_en": "Define Lanes",
        "description_tr": "Kulvar sayısı ve amaçlarını belirleyin.",
        "description_en": "Set lane count and purposes.",
        "route": "/pools",
    },
    {
        "id": "instructor",
        "title_tr": "İlk Eğitmeni Ekle",
        "title_en": "Add the First Instructor",
        "description_tr": "En az bir eğitmen kaydı oluşturun.",
        "description_en": "Create at least one instructor.",
        "route": "/instructors?action=new",
    },
    {
        "id": "student",
        "title_tr": "İlk Öğrenciyi Ekle",
        "title_en": "Add the First Student",
        "description_tr": "İlk öğrenci kaydınızı açın.",
        "description_en": "Create your first student record.",
        "route": "/students?action=new",
    },
    {
        "id": "ai",
        "title_tr": "AI Ayarları",
        "title_en": "AI Settings",
        "description_tr": "Yerel veya bulut AI bağlantısını yapılandırın (isteğe bağlı).",
        "description_en": "Configure local or cloud AI (optional).",
        "route": "/ai",
    },
    {
        "id": "backup",
        "title_tr": "Backup Ayarları",
        "title_en": "Backup Settings",
        "description_tr": "Otomatik yedeklemeyi etkinleştirin.",
        "description_en": "Enable scheduled backups.",
        "route": "/settings?tab=backup",
    },
    {
        "id": "finish",
        "title_tr": "Kurulumu Tamamla",
        "title_en": "Finish Setup",
        "description_tr": "Hazırsınız! Eğitim Merkezi'nden devam edebilirsiniz.",
        "description_en": "You're ready! Continue from the Training Center.",
        "route": "/training",
    },
]


def tutorials_for_roles(role_codes: list[str]) -> list[str]:
    """Kullanıcının rollerine göre önerilen eğitim kimliklerini döndürür."""
    track_ids: list[str] = []
    for code in role_codes:
        track_ids.extend(ROLE_TRACKS.get(code, []))

    tutorial_ids: list[str] = []
    for track in TRACKS:
        if track["id"] in track_ids:
            tutorial_ids.extend(track["tutorials"])

    seen: set[str] = set()
    ordered: list[str] = []
    for tutorial_id in tutorial_ids:
        if tutorial_id not in seen:
            seen.add(tutorial_id)
            ordered.append(tutorial_id)
    return ordered or [t.id for t in TUTORIALS[:3]]
