"""add HSP rights receipts, consent-notice separation and provider evidence

Revision ID: eb76aa93f852
Revises: 0ca413b128ea
Create Date: 2026-08-18 11:32:49.592901

"""

from __future__ import annotations

from collections.abc import Sequence

from datetime import datetime, timezone

import sqlalchemy as sa
from alembic import op

revision: str = "eb76aa93f852"
down_revision: str | None = "0ca413b128ea"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hsp_notice_versions",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("body_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hsp_notice_versions")),
    )
    with op.batch_alter_table("hsp_notice_versions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_hsp_notice_active", ["code", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hsp_notice_versions_code"), ["code"], unique=False
        )

    op.create_table(
        "hsp_provider_evidence",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=True),
        sa.Column("retains_data", sa.Boolean(), nullable=True),
        sa.Column("trains_on_data", sa.Boolean(), nullable=True),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("dpa_evidence", sa.String(length=200), nullable=True),
        sa.Column("transfer_mechanism", sa.String(length=60), nullable=True),
        sa.Column("max_classification", sa.String(length=20), nullable=False),
        sa.Column("reviewed_by_user_id", sa.Integer(), nullable=True),
        sa.Column("reviewed_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_hsp_provider_evidence_reviewed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hsp_provider_evidence")),
        sa.UniqueConstraint("provider", name=op.f("uq_hsp_provider_evidence_provider")),
    )
    op.create_table(
        "hsp_rights_receipts",
        sa.Column("domain", sa.String(length=10), nullable=False),
        sa.Column("operation", sa.String(length=80), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column("personal_kind", sa.String(length=20), nullable=False),
        sa.Column("concerns_child", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=True),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_role", sa.String(length=40), nullable=True),
        sa.Column("subject_kind", sa.String(length=20), nullable=True),
        sa.Column("subject_ref", sa.String(length=64), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("chain_hash", sa.String(length=64), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_hsp_rights_receipts_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hsp_rights_receipts")),
        sa.UniqueConstraint(
            "chain_hash", name=op.f("uq_hsp_rights_receipts_chain_hash")
        ),
    )
    with op.batch_alter_table("hsp_rights_receipts", schema=None) as batch_op:
        batch_op.create_index("ix_hsp_receipt_decision", ["decision"], unique=False)
        batch_op.create_index(
            "ix_hsp_receipt_subject", ["subject_kind", "subject_ref"], unique=False
        )
        batch_op.create_index("ix_hsp_receipt_time", ["occurred_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_hsp_rights_receipts_domain"), ["domain"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hsp_rights_receipts_occurred_at"),
            ["occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_hsp_rights_receipts_operation"), ["operation"], unique=False
        )

    op.create_table(
        "hsp_consent_records",
        sa.Column("subject_kind", sa.String(length=20), nullable=False),
        sa.Column("subject_id", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(length=60), nullable=False),
        sa.Column("granted", sa.Boolean(), nullable=False),
        sa.Column("notice_version_id", sa.Integer(), nullable=True),
        sa.Column("channel", sa.String(length=30), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("given_by_guardian_id", sa.Integer(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Integer(), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=True),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["given_by_guardian_id"],
            ["guardians.id"],
            name=op.f("fk_hsp_consent_records_given_by_guardian_id_guardians"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["notice_version_id"],
            ["hsp_notice_versions.id"],
            name=op.f("fk_hsp_consent_records_notice_version_id_hsp_notice_versions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["users.id"],
            name=op.f("fk_hsp_consent_records_recorded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hsp_consent_records")),
    )
    with op.batch_alter_table("hsp_consent_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_hsp_consent_purpose", ["purpose", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hsp_consent_records_granted_at"),
            ["granted_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_hsp_consent_subject", ["subject_kind", "subject_id"], unique=False
        )

    op.create_table(
        "hsp_consent_withdrawals",
        sa.Column("consent_id", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("requested_by_user_id", sa.Integer(), nullable=True),
        sa.Column("propagated", sa.Boolean(), nullable=False),
        sa.Column("propagation_notes", sa.Text(), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["consent_id"],
            ["hsp_consent_records.id"],
            name=op.f("fk_hsp_consent_withdrawals_consent_id_hsp_consent_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_hsp_consent_withdrawals_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hsp_consent_withdrawals")),
    )
    with op.batch_alter_table("hsp_consent_withdrawals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hsp_consent_withdrawals_consent_id"),
            ["consent_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_hsp_consent_withdrawals_withdrawn_at"),
            ["withdrawn_at"],
            unique=False,
        )

    # ### end Alembic commands ###

    _backfill_legacy_consent()


def _backfill_legacy_consent() -> None:
    """Eski `students.consent_given` verisini yeni yapıya taşır.

    Eski alan aydınlatma ile açık rızayı tek boolean'da birleştiriyordu; hangi
    işlemin gerçekten onaylandığı kayıttan çıkarılamaz. Bu yüzden veri
    `legacy_unseparated` amacıyla taşınır ve `evidence_hash` boş bırakılır:
    kayıt korunur ama geçerli bir açık rıza yerine geçmez. Ayrıştırma için
    insan incelemesi gerekir.

    Eski sütun silinmez — veri kaybı olmaması için yerinde bırakılır.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {col["name"] for col in inspector.get_columns("students")}
    if "consent_given" not in columns:
        return

    rows = bind.execute(
        sa.text(
            "SELECT id, consent_given, consent_date FROM students "
            "WHERE consent_given = 1"
        )
    ).fetchall()
    if not rows:
        return

    now = datetime.now(timezone.utc)
    bind.execute(
        sa.text(
            "INSERT INTO hsp_consent_records "
            "(subject_kind, subject_id, purpose, granted, channel, language, "
            " granted_at, is_active, created_at, updated_at) "
            "VALUES (:kind, :sid, :purpose, :granted, :channel, :lang, "
            "        :granted_at, :active, :created, :updated)"
        ),
        [
            {
                "kind": "student",
                "sid": row[0],
                "purpose": "legacy_unseparated",
                "granted": True,
                "channel": "migrated",
                "lang": "tr",
                "granted_at": row[2] or now,
                "active": True,
                "created": now,
                "updated": now,
            }
            for row in rows
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hsp_consent_withdrawals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hsp_consent_withdrawals_withdrawn_at"))
        batch_op.drop_index(batch_op.f("ix_hsp_consent_withdrawals_consent_id"))

    op.drop_table("hsp_consent_withdrawals")
    with op.batch_alter_table("hsp_consent_records", schema=None) as batch_op:
        batch_op.drop_index("ix_hsp_consent_subject")
        batch_op.drop_index(batch_op.f("ix_hsp_consent_records_granted_at"))
        batch_op.drop_index("ix_hsp_consent_purpose")

    op.drop_table("hsp_consent_records")
    with op.batch_alter_table("hsp_rights_receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hsp_rights_receipts_operation"))
        batch_op.drop_index(batch_op.f("ix_hsp_rights_receipts_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_hsp_rights_receipts_domain"))
        batch_op.drop_index("ix_hsp_receipt_time")
        batch_op.drop_index("ix_hsp_receipt_subject")
        batch_op.drop_index("ix_hsp_receipt_decision")

    op.drop_table("hsp_rights_receipts")
    op.drop_table("hsp_provider_evidence")
    with op.batch_alter_table("hsp_notice_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hsp_notice_versions_code"))
        batch_op.drop_index("ix_hsp_notice_active")

    op.drop_table("hsp_notice_versions")
    # ### end Alembic commands ###
